# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Qabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=2000)),
                ('votes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('qabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Qabase')),
            ],
            options={
                'verbose_name': 'Answer',
                'ordering': ['-timestamp'],
            },
            bases=('qa.qabase',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Qabase')),
                ('topic', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['-timestamp'],
            },
            bases=('qa.qabase',),
        ),
    ]
