# Generated by Django 2.0.2 on 2018-02-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=2000)),
                ('votes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('qabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Qabase')),
            ],
            options={
                'verbose_name': 'Answer',
            },
            bases=('qa.qabase',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qa.Qabase')),
                ('topic', models.CharField(max_length=100)),
                ('ans_list', models.ManyToManyField(to='qa.Answer')),
                ('tag_list', models.ManyToManyField(to='qa.Category')),
            ],
            options={
                'verbose_name': 'Question',
            },
            bases=('qa.qabase',),
        ),
        migrations.AddField(
            model_name='qabase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Euser'),
        ),
    ]
