# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabase',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters_list', to='users.Euser'),
        ),
        migrations.AddField(
            model_name='qabase',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters_list', to='users.Euser'),
        ),
        migrations.AddField(
            model_name='qabase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Euser'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans_list',
            field=models.ManyToManyField(blank=True, to='qa.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag_list',
            field=models.ManyToManyField(to='qa.Category'),
        ),
    ]
