# Generated by Django 2.0.2 on 2018-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterField(
            model_name='question',
            name='ans_list',
            field=models.ManyToManyField(blank=True, to='qa.Answer'),
        ),
    ]
