# Generated by Django 2.0.2 on 2018-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('qa', '0002_auto_20180205_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Question'},
        ),
        migrations.AddField(
            model_name='qabase',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters_list', to='users.Euser'),
        ),
        migrations.AddField(
            model_name='qabase',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters_list', to='users.Euser'),
        ),
    ]
