# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('qa', '0002_auto_20180207_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('ans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Answer')),
                ('downvoters', models.ManyToManyField(blank=True, related_name='cmnt_downvoters_list', to='users.Euser')),
                ('que', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Question')),
                ('upvoters', models.ManyToManyField(blank=True, related_name='cmnt_upvoters_list', to='users.Euser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Euser')),
            ],
        ),
    ]
